### ISSUE TITLE
Use renamed component-emitter which has license pkg json field

### ISSUE THREAD

**Issue by jorenbroekema** [juliangruber/stream#11]
Right now this package depends on `emitter-component`, this package was renamed to `component-emitter` and the issue with the previous one is that it has a licensing issue, because there is no license field in its published pkg json on NPM, this causes unclear licensing issue for dependents which is a significant problem in enterprise environments.

Would it be possible to publish a new version of stream (0.0.3) with that component-emitter dependency upgraded to latest? I'm happy to open a PR

**Comment by juliangruber** [comment]
This project is old :D I can try to publish a new version! Would be great if you could open a PR for it
